[
  {
    id: "1",
    uhd: "1003",
    name: "Smith",
    spacealists: "Doctor Ken",
    Date: "24-08-2022",
    time: "09:am",
    image: "/assets/adedoyin.jpg",
  },
  {
    id: "2",
    uhd: "1005",
    name: "Adedayo",
    spacealists: "Doctor Roselyn",
    Date: "32-06-2042",
    time: "10:am",
    image: "/assets/girl.jpg",
  },
  {
    id: "3",
    uhd: "1078",
    name: "Jones",
    spacealists: "Doctor Ken",
    Date: "24-08-2022",
    time: "09:am",
    image: "/assets/nduka.jpg",
  },
  {
    id: "4",
    uhd: "1003",
    name: "Gideon",
    spacealists: "Doctor Roselyn",
    Date: "32-06-2042",
    time: "10:am",
    image: "/assets/nduka.jpg",
  },
  {
    id: "5",
    uhd: "1003",
    name: "Tonia",
    spacealists: "Doctor Ken",
    Date: "24-08-2022",
    time: "09:am",
    image: "/assets/lanu.jpg",
  },
  {
    id: "6",
    uhd: "1056",
    name: "Ruth",
    spacealists: "Doctor Roselyn",
    Date: "32-06-2042",
    time: "10:am",
    image: "/assets/lanu.jpg",
  },
];
